### ISSUE TITLE
Basic question - process exits..

### ISSUE THREAD

**Issue by richp10** [kadet1090/nucleus#2]
Sorry for such a basic question - my first time with react..

Following code runs straight through, process finished with exit code 0 - rather than awaiting incoming XMPP.. I am obviously missing something! I was assuming this would run as an XMPP client, listening for incoming stanza's and triggering the events. 

Thanks for any pointers..

```
  $loop = React\EventLoop\Factory::create();
  $client = new Kadet\Xmpp\XmppClient(new \Kadet\Xmpp\Jid('bot@mydomain.org/daemon'),
      [
          'loop'     => $loop,
          'password' => 'passBoo'
      ]);

  $client->on('stream.open', function (Kadet\Xmpp\Xml\XmlElement $stream) {
    echo print_r($stream);
  });

  $client->on('stream.error', function (Kadet\Xmpp\Stream\Error $error) {
    echo print_r($error);
  });

  $client->on('exception', function (Exception $exception) {
    echo print_r($exception);
  });

  $client->on('element', function (Kadet\Xmpp\Xml\XmlElement $element) {
    echo print_r($element);
  });

  $client->on('connect', function (StreamDuplexInterface $stream) {
    echo 'Connected';
  });

  $client->on('close', function () {
    echo 'Closed';
  });

  $loop->run();
```

**Comment by kadet1090** [comment]
Hi, it's my fault 😞 I forgot to put `$client->connect();` in readme just before `$loop->run();`, nevertheless I've corrected that. Thx for spotting!

**Comment by richp10** [comment]
That worked great, thanks.. I am here to find the bugs that trip up the ignorant ;)
