### ISSUE TITLE
dns lookups

### ISSUE THREAD

**Issue by richp10** [kadet1090/nucleus#3]
I am having difficulty with the dnsResolver - so connect still fails. 

```
  $client = new Kadet\Xmpp\XmppClient(new \Kadet\Xmpp\Jid('bot@mydomain.org'),
      [
          'loop'     => $loop,
          'password' => 'password'
      ]);
```

On client->connect, this fails with exception at line 50 of TcpXmppConnector.php

Putting  echo print_r($this->_resolver); at line 37 - the resolver looks like this:

```
Kadet\Xmpp\Utils\DnsResolver Object
(
    [_results:Kadet\Xmpp\Utils\DnsResolver:private] => 
    [_pool:Kadet\Xmpp\Utils\DnsResolver:private] => Array
        (
            [_xmpp-client._tcp.mydomain.org] => 33554432
            [mydomain.org] => 134217728
        )
)
```

So block in lines 38 to 47 is not run - the resolver is not finding the ip and port. 

As experiment, I tried setting the jid to use domain google.com (just to see if it would resolve that domain).  This resulted in a different error: 

ErrorException: Undefined index: target in \vendor\kadet\nucleus\Utils\DnsResolver.php:58

I am on windows and php7. 

Any thoughts?

**Comment by kadet1090** [comment]
Hmm, what is the exact domain that you're trying to resolve? I've resolved issue with google, but it seems that your dns is not able to resolve that domain (this is only scenario where it throws exception). Tell me what is the result (if there is any) of 

```
 nslookup -type=SRV _xmpp-client._tcp.mydomain.org
```

and

```
 nslookup -type=A mydomain.org
```

commands.

**Comment by richp10** [comment]
With that change, I get same error with google.com and my domain (recoveryonline.org) - undefined index target in DnsResolver.php:58 - if I debug at line 56 - $this->_results is an empty array.  So progress of sorts!

Using the nslookup command I get the correct result for both google.com and recoveryonline.org

Maybe not relevent, but one thing I was wondering is that I don't seem to be setting the dns server to use; when you use the reactphp/dns client you specify where to do the lookup..

```
$factory = new React\Dns\Resolver\Factory();
$dns = $factory->create('8.8.8.8', $loop);
```

Or am I missing something bigger - do you use the reactphp/dns object but I am not using this in my code?

**Comment by kadet1090** [comment]
Well, that's really strange because i'm able to resolve that and connect to that server. Have you tried the most recent commit? I'm not using `reactphp/dns` because it's not package meant for simple hostname resolving - it's more like library for querying specific DNS server, and it's just a lot simpler to rely on mechanism provided by system, which uses server configured for network.

![pics](https://dl.dropboxusercontent.com/u/60020102/ShareX/2016-11/2016-11-13_15-27-06-520.png)

**Comment by richp10** [comment]
Thanks for that; must be something about my local setup. I will do some experimenting and maybe try it on a linux machine / check hosts file and so on.. Will let you know what I find.. explanation re: reactphp/dns makes complete sense thanks...
